services:
    _defaults:
        autowire: true
        autoconfigure: true

    Weglot\DoctrinePostgresEnum\Doctrine\Driver\EnumColumnMiddleware:
    Weglot\DoctrinePostgresEnum\Doctrine\Platform\EnumMetaDataProvider:
